from typing import Mapping, Type

from sqlalchemy import inspect
from sqlalchemy.orm import NO_VALUE

from src.app.shared_kernel.utils.static_analys.assertion_funcs import (
    ensure_isimplementation,
)
from src.app.data_access.entity_source.sources import SqlAlchemyEntitySource
from src.app.data_access.orm.base.base_orm_models import SqlAlchemyBaseModel
from src.app.shared_kernel.ports.domain.entity_proxy import EntityProxy
from src.app.shared_kernel.ports.domain.entity_source_proto import EntitySourceProto
from src.app.shared_kernel.ports.factories.entity_source_factory import (
    EntitySourceFactoryProto,
)
from src.app.shared_kernel.utils.functions.uuid_funcs import uuid7


class SqlAlchemyEntitySourceFactory(EntitySourceFactoryProto):
    """
    Sql alchemy orm entity source factory
    Creates an empty orm entity object as
    entity proxy source.

    Args:
        domain_model_to_orm_model_map (Mapping[Type[EntityProxy], Type[EntitySource]]):
            Mapping from domain model type to orm model type.
    """

    def __init__(
        self,
        domain_model_to_orm_model_map: Mapping[
            Type[EntityProxy], Type[SqlAlchemyBaseModel]
        ],
    ) -> None:
        self._map = domain_model_to_orm_model_map
        self._domain_model_orm_map = domain_model_to_orm_model_map
        self._orm_model_domain_entity_map = {
            v: k for k, v in self._domain_model_orm_map.items()
        }

    def empty(self, entity: Type[EntityProxy], **init_kwargs) -> EntitySourceProto:
        primitive_kwargs = {}
        related, related_collections = {}, {}

        model_cls = self._domain_model_orm_map[entity]

        for k, v in init_kwargs.items():
            if isinstance(v, EntityProxy):
                related[k] = v
            elif isinstance(v, list) and len(v) > 0 and isinstance(v[0], EntityProxy):
                related_collections[k] = v
            else:
                primitive_kwargs[k] = v

        if not model_cls:
            raise KeyError(f"Orm model for {entity} not found.")

        data_source = model_cls(**primitive_kwargs)

        # Stamp the id now rather than at INSERT. UUIDv7 is generated by the
        # application, so there is nothing to wait for — and an aggregate that
        # already knows its id can raise events and build related rows without
        # a flush round trip first.
        if getattr(data_source, "id", None) is None:
            data_source.id = uuid7()

        e_source = SqlAlchemyEntitySource(obj=data_source)

        for k, entity in related.items():
            e_source.set_related_entity(k, entity)

        for k, entities in related_collections.items():
            e_source.set_related_entities(k, entities)

        return e_source

    def from_source(self, data_source: SqlAlchemyBaseModel) -> EntitySourceProto:
        src = SqlAlchemyEntitySource(obj=data_source)

        mapper = inspect(data_source.__class__)
        state = inspect(data_source)

        for rel in mapper.relationships:
            attr_state = state.attrs[rel.key]

            if attr_state.loaded_value is NO_VALUE:
                continue  # relationship не загружен, lazy="raise" не триггерим

            orm_value = attr_state.value

            if orm_value is None:
                continue

            entity_cls = self._orm_model_domain_entity_map.get(rel.entity.entity, None)

            if entity_cls is None:
                continue

            if rel.uselist:
                related_entities = [
                    entity_cls(self.from_source(obj)) for obj in orm_value
                ]
                src.set_related_entities(rel.key, related_entities)
            else:
                related_source = entity_cls(self.from_source(orm_value))
                src.set_related_entity(rel.key, related_source)

        return src


ensure_isimplementation(SqlAlchemyEntitySourceFactory, EntitySourceFactoryProto)
