import regex

USER_NAME_MAX_LENGTH = 50
USER_NAME_MIN_LENGTH = 1
USER_NAME_REGEX = regex.compile(r"^\p{L}+(?:[\s-]\p{L}+)*$", regex.UNICODE)

USER_EMAIL_MAX_LENGTH = 254
USER_EMAIL_MIN_LENGTH = 5
USER_EMAIL_REGEX = regex.compile(r"^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$")

USER_PHONE_MAX_LENGTH = 15
USER_PHONE_MIN_LENGTH = 12
USER_PHONE_REGEX = regex.compile(r"^\+?[1-9]\d{7,14}$")

USER_PASSWORD_MIN_LENGTH = 8
USER_PASSWORD_MAX_LENGTH = 128

USER_ADDRESS_MAX_LENGTH = 500
USER_DESCRIPTION_MAX_LENGTH = 5000

OTP_MIN_LENGTH = 6
OTP_MAX_LENGTH = 6
