DECIMAL_BALANCE_DIGITS = 30
DECIMAL_BALANCE_PLACES = 4

LONG_DECIMAL_DIGITS = 30
LONG_DECIMAL_PLACES = 4

DECIMAL_PRICE_DIGITS = 14
DECIMAL_PRICE_PLACES = 4

DECIMAL_RATE_DIGITS = 12
DECIMAL_RATE_PLACES = 6

DECIMAL_DISCOUNT_DIGITS = 5
DECIMAL_DISCOUNT_PLACES = 2

DECIMAL_AMOUNT_DIGITS = 14
DECIMAL_AMOUNT_PLACES = 4
