"""initial schema: identity, blob, telemetry

Revision ID: 0001
Revises:
Create Date: 2026-09-06

Hand-written rather than autogenerated for one reason: ``identity_user.avatar_id``
and ``blob_object.created_by_id`` reference each other, so neither table can be
created with both foreign keys already in place. The cross-references are added
after both tables exist.
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "identity_user",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=False),
        sa.Column("password", sa.String(length=128), nullable=True),
        sa.Column("phone", sa.String(length=15), nullable=True),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("address", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("information", sa.Text(), nullable=True),
        sa.Column("avatar_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("email_confirmed", sa.Boolean(), nullable=False),
        sa.Column(
            "date_joined",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("last_login_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.SmallInteger(), nullable=False),
        sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deactivated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("activated_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("deactivated_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["activated_by_id"],
            ["identity_user.id"],
            name="fk_identity_user__activated_by_id__identity_user__id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["deactivated_by_id"],
            ["identity_user.id"],
            name="fk_identity_user__deactivated_by_id__identity_user__id",
            ondelete="SET NULL",
        ),
    )
    op.create_index(
        "ix_identity_user_email", "identity_user", ["email"], unique=True
    )

    op.create_table(
        "blob_object",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("kind", sa.SmallInteger(), nullable=False),
        sa.Column("content_type", sa.String(length=120), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("medium_path", sa.String(length=500), nullable=True),
        sa.Column("thumbnail_path", sa.String(length=500), nullable=True),
        sa.Column("created_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("updated_by_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["identity_user.id"],
            name="fk_blob_object__created_by_id__identity_user__id",
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by_id"],
            ["identity_user.id"],
            name="fk_blob_object__updated_by_id__identity_user__id",
            ondelete="SET NULL",
        ),
    )

    # The other half of the cycle, now that both tables exist.
    op.create_foreign_key(
        "fk_identity_user__avatar_id__blob_object__id",
        "identity_user",
        "blob_object",
        ["avatar_id"],
        ["id"],
        ondelete="SET NULL",
    )

    op.create_table(
        "identity_otp",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("otp", sa.String(length=40), nullable=True),
        sa.Column("content_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("kind", sa.SmallInteger(), nullable=False),
        sa.Column("used_at", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.BigInteger(), nullable=False),
        sa.Column("target_value", sa.String(length=254), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_identity_otp__content__kind",
        "identity_otp",
        ["content_id", "content_type", "kind"],
    )

    op.create_table(
        "identity_api_key",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("key", sa.LargeBinary(length=32), nullable=False),
        sa.Column("status", sa.SmallInteger(), nullable=False),
        sa.Column("last_used_at", sa.Integer(), nullable=True),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["identity_user.id"], ondelete="CASCADE"
        ),
    )
    op.create_index("ix_identity_api_key_key", "identity_api_key", ["key"])

    op.create_table(
        "telemetry_log",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("trace_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("service", sa.String(length=64), nullable=False),
        sa.Column("level", sa.String(length=16), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("epoch", sa.Double(), nullable=False),
        sa.Column("exec_ms", sa.Double(), nullable=True),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("method", sa.String(length=8), nullable=True),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("url_params", postgresql.JSONB(), nullable=True),
        sa.Column("data", postgresql.JSONB(), nullable=True),
        sa.Column("status_code", sa.SmallInteger(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_telemetry_log__trace_id", "telemetry_log", ["trace_id"])
    op.create_index(
        "idx_telemetry_log__service__ts", "telemetry_log", ["service", "ts"]
    )
    op.create_index("idx_telemetry_log__user_id__ts", "telemetry_log", ["user_id", "ts"])
    op.create_index("idx_telemetry_log__level", "telemetry_log", ["level"])
    op.create_index("idx_telemetry_log__status_code", "telemetry_log", ["status_code"])

    op.create_table(
        "telemetry_log_traceback",
        sa.Column("log_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("traceback", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("log_id", name="pk_telemetry_log_traceback__log_id"),
        sa.ForeignKeyConstraint(
            ["log_id"],
            ["telemetry_log.id"],
            name="pk_telemetry_log_traceback__log_id__telemetry_log__id",
            ondelete="CASCADE",
        ),
    )


def downgrade() -> None:
    op.drop_table("telemetry_log_traceback")
    op.drop_table("telemetry_log")
    op.drop_table("identity_api_key")
    op.drop_table("identity_otp")
    # Break the cycle before dropping either side of it.
    op.drop_constraint(
        "fk_identity_user__avatar_id__blob_object__id",
        "identity_user",
        type_="foreignkey",
    )
    op.drop_table("blob_object")
    op.drop_table("identity_user")
