from typing import Self, Protocol, TypeVar, runtime_checkable

TRepo = TypeVar("TRepo")


@runtime_checkable
class UnitOfWorkProto(Protocol):
    async def commit(self) -> None: ...
    async def rollback(self) -> None: ...
    async def flush(self) -> None: ...

    # async def make_repo(self, repo_t: Type[TRepo]) -> TRepo: ...
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
