from typing import Protocol, Union, runtime_checkable


@runtime_checkable
class PasswordServiceProto(Protocol):
    def hash_password(self, password: str) -> bytes: ...
    def generate_salt(self) -> bytes: ...

    def needs_rehash(self, hashed_password: Union[str, bytes]) -> bool: ...

    def verify_password(
        self,
        password: Union[str, bytes],
        hashed_password: Union[str, bytes],
    ) -> bool: ...

    def get_bytes(self, password: Union[str, bytes]) -> bytes: ...
    def to_bytes(self, value: str) -> bytes: ...
